version: "3.9"

services:
  db:
    image: postgres:15
    container_name: finmark-db
    environment:
      POSTGRES_DB: finmark_users
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: chuman121001
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  auth-service:
    build: ./auth-service
    container_name: finmark-auth
    ports:
      - "5002:5002"
    env_file:
      - ./auth-service/.env
    depends_on:
      - db
    restart: on-failure

  client:
    build: ./client
    container_name: finmark-client
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - auth-service
    tty: true
    stdin_open: true

volumes:
  db-data:
