version: "3.9"

services:
  db:
    image: postgres:15
    container_name: finmark-db
    environment:
      POSTGRES_DB: finmark_users
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: chuman121001
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  auth-service:
    build: ./auth-service
    container_name: finmark-auth
    ports:
      - "5002:5002"
    environment:
      PORT: 5002
      DB_HOST: db
      DB_NAME: finmark_users
      DB_USER: postgres
      DB_PASS: chuman121001
      JWT_SECRET: 481725203908d81ef0fedb8a84c1632293e249179b9b1308cc8b01976d757ebb
    depends_on:
      - db
    restart: on-failure

volumes:
  db-data: